//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/VUAJ/Zoom/InputActions/vUAJ-DefaultActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @VUAJDefaultActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @VUAJDefaultActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""vUAJ-DefaultActions"",
    ""maps"": [
        {
            ""name"": ""vUAJ_Actions"",
            ""id"": ""2c42cce1-7065-4522-9d03-5dd08c607dd3"",
            ""actions"": [
                {
                    ""name"": ""ActivateMagnifyingGlass"",
                    ""type"": ""Button"",
                    ""id"": ""4302b31e-bb61-4adc-bca2-b445a035c613"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveMagnifyingGlass"",
                    ""type"": ""Value"",
                    ""id"": ""f23d5d31-591e-44db-aad4-c585abb5e28d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ExpandMagnifyingGlass"",
                    ""type"": ""Button"",
                    ""id"": ""cf2cc4c8-29cb-4978-a402-7a5fe11603c0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ReduceMagnifyingGlass"",
                    ""type"": ""Button"",
                    ""id"": ""e7b66cc2-c282-470e-9ada-6a50d5c9e594"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c2e8afd0-bfa3-445f-a130-cb042bc8273f"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""ActivateMagnifyingGlass"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""VerticalMovement"",
                    ""id"": ""925f0e9b-cb45-428e-82a1-711c568e602e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveMagnifyingGlass"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""3112ed56-b78b-436c-a6a5-f135dfdd371b"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""MoveMagnifyingGlass"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""7e289d0e-4af6-4766-b0cb-4db71e11275f"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""MoveMagnifyingGlass"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""9cda750d-9351-4bf7-badf-5bb4696a465a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""MoveMagnifyingGlass"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""4878dd76-7e91-4a5a-b7d1-94c27f510b82"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""MoveMagnifyingGlass"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e0e8557d-8c96-431d-a92e-538bbfd11b59"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ExpandMagnifyingGlass"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25786fdd-d3e6-4b58-9862-a690370687db"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReduceMagnifyingGlass"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // vUAJ_Actions
        m_vUAJ_Actions = asset.FindActionMap("vUAJ_Actions", throwIfNotFound: true);
        m_vUAJ_Actions_ActivateMagnifyingGlass = m_vUAJ_Actions.FindAction("ActivateMagnifyingGlass", throwIfNotFound: true);
        m_vUAJ_Actions_MoveMagnifyingGlass = m_vUAJ_Actions.FindAction("MoveMagnifyingGlass", throwIfNotFound: true);
        m_vUAJ_Actions_ExpandMagnifyingGlass = m_vUAJ_Actions.FindAction("ExpandMagnifyingGlass", throwIfNotFound: true);
        m_vUAJ_Actions_ReduceMagnifyingGlass = m_vUAJ_Actions.FindAction("ReduceMagnifyingGlass", throwIfNotFound: true);
    }

    ~@VUAJDefaultActions()
    {
        UnityEngine.Debug.Assert(!m_vUAJ_Actions.enabled, "This will cause a leak and performance issues, VUAJDefaultActions.vUAJ_Actions.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // vUAJ_Actions
    private readonly InputActionMap m_vUAJ_Actions;
    private List<IVUAJ_ActionsActions> m_VUAJ_ActionsActionsCallbackInterfaces = new List<IVUAJ_ActionsActions>();
    private readonly InputAction m_vUAJ_Actions_ActivateMagnifyingGlass;
    private readonly InputAction m_vUAJ_Actions_MoveMagnifyingGlass;
    private readonly InputAction m_vUAJ_Actions_ExpandMagnifyingGlass;
    private readonly InputAction m_vUAJ_Actions_ReduceMagnifyingGlass;
    public struct VUAJ_ActionsActions
    {
        private @VUAJDefaultActions m_Wrapper;
        public VUAJ_ActionsActions(@VUAJDefaultActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @ActivateMagnifyingGlass => m_Wrapper.m_vUAJ_Actions_ActivateMagnifyingGlass;
        public InputAction @MoveMagnifyingGlass => m_Wrapper.m_vUAJ_Actions_MoveMagnifyingGlass;
        public InputAction @ExpandMagnifyingGlass => m_Wrapper.m_vUAJ_Actions_ExpandMagnifyingGlass;
        public InputAction @ReduceMagnifyingGlass => m_Wrapper.m_vUAJ_Actions_ReduceMagnifyingGlass;
        public InputActionMap Get() { return m_Wrapper.m_vUAJ_Actions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(VUAJ_ActionsActions set) { return set.Get(); }
        public void AddCallbacks(IVUAJ_ActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_VUAJ_ActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_VUAJ_ActionsActionsCallbackInterfaces.Add(instance);
            @ActivateMagnifyingGlass.started += instance.OnActivateMagnifyingGlass;
            @ActivateMagnifyingGlass.performed += instance.OnActivateMagnifyingGlass;
            @ActivateMagnifyingGlass.canceled += instance.OnActivateMagnifyingGlass;
            @MoveMagnifyingGlass.started += instance.OnMoveMagnifyingGlass;
            @MoveMagnifyingGlass.performed += instance.OnMoveMagnifyingGlass;
            @MoveMagnifyingGlass.canceled += instance.OnMoveMagnifyingGlass;
            @ExpandMagnifyingGlass.started += instance.OnExpandMagnifyingGlass;
            @ExpandMagnifyingGlass.performed += instance.OnExpandMagnifyingGlass;
            @ExpandMagnifyingGlass.canceled += instance.OnExpandMagnifyingGlass;
            @ReduceMagnifyingGlass.started += instance.OnReduceMagnifyingGlass;
            @ReduceMagnifyingGlass.performed += instance.OnReduceMagnifyingGlass;
            @ReduceMagnifyingGlass.canceled += instance.OnReduceMagnifyingGlass;
        }

        private void UnregisterCallbacks(IVUAJ_ActionsActions instance)
        {
            @ActivateMagnifyingGlass.started -= instance.OnActivateMagnifyingGlass;
            @ActivateMagnifyingGlass.performed -= instance.OnActivateMagnifyingGlass;
            @ActivateMagnifyingGlass.canceled -= instance.OnActivateMagnifyingGlass;
            @MoveMagnifyingGlass.started -= instance.OnMoveMagnifyingGlass;
            @MoveMagnifyingGlass.performed -= instance.OnMoveMagnifyingGlass;
            @MoveMagnifyingGlass.canceled -= instance.OnMoveMagnifyingGlass;
            @ExpandMagnifyingGlass.started -= instance.OnExpandMagnifyingGlass;
            @ExpandMagnifyingGlass.performed -= instance.OnExpandMagnifyingGlass;
            @ExpandMagnifyingGlass.canceled -= instance.OnExpandMagnifyingGlass;
            @ReduceMagnifyingGlass.started -= instance.OnReduceMagnifyingGlass;
            @ReduceMagnifyingGlass.performed -= instance.OnReduceMagnifyingGlass;
            @ReduceMagnifyingGlass.canceled -= instance.OnReduceMagnifyingGlass;
        }

        public void RemoveCallbacks(IVUAJ_ActionsActions instance)
        {
            if (m_Wrapper.m_VUAJ_ActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IVUAJ_ActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_VUAJ_ActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_VUAJ_ActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public VUAJ_ActionsActions @vUAJ_Actions => new VUAJ_ActionsActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    public interface IVUAJ_ActionsActions
    {
        void OnActivateMagnifyingGlass(InputAction.CallbackContext context);
        void OnMoveMagnifyingGlass(InputAction.CallbackContext context);
        void OnExpandMagnifyingGlass(InputAction.CallbackContext context);
        void OnReduceMagnifyingGlass(InputAction.CallbackContext context);
    }
}
